- name: Ansible updates/upgrades OS packages
  strategy: free
  gather_facts: no
  hosts: all
  become: true
  tasks:
    - name: Update all packages on Ubuntu
      apt:
        update_cache: yes
        cache_valid_time: 86400  # 1 day
        upgrade: dist


    - name: Check if reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot_required get_md5=no

    - name: Reboot the host if needed
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 180
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists


    - name: Verify new update (optional)
      command: uname -mrs
      register: uname_result
    - name: Verify uptime (optional)
      command: uptime -p
      register: uptime_result
    - name: Display new kernel version and uptime
      debug:
        var: uname_result.stdout_lines, uptime_result.stdout_lines
