#cloud-config
package_update: true
package_upgrade: true
packages:
  - nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      upstream backend_servers {
          server backend1.mshome.net;
          server backend2.mshome.net;
          server backend3.mshome.net;
      }
      server {
          listen 80 default_server;
          location / {
              proxy_http_version 1.1;
              proxy_set_header HOST $host;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection keep-alive;
              proxy_cache_bypass $http_upgrade;
              proxy_pass http://backend_servers;
          }
      }
runcmd:
  - service nginx restart
