- name: Ansible shutdown OS and poweroff VM
  strategy: free
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Shutting down the remote host
      community.general.shutdown:
        msg: "Shutdown initiated by Ansible"
        delay: 3

    - name: Validate the shutdown
      wait_for:
        shell ping -q -c 1 -W 1 {{ ansible_ssh_host }}
      register: res
      retries: 5
      until: ('100.0% packet loss' in res.stdout)
      failed_when: ('100.0% packet loss' not in res.stdout)
      ignore_errors: yes
      changed_when: False
